steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/fx-library/mforceile', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/fx-library/mforceile']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mforceile'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/fx-library/mforceile'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/fx-library/mforceile'

options:
  logging: CLOUD_LOGGING_ONLY
